export const flags = {
  IN: require('@homzhub/common/src/assets/flags/india-flag.png'),
  US: require('@homzhub/common/src/assets/flags/united-states-of-america-flag.png'),
  AU: require('@homzhub/common/src/assets/flags/austallia-flag.png'),
  SG: require('@homzhub/common/src/assets/flags/singapore-flag.png'),
  AE: require('@homzhub/common/src/assets/flags/united-arab-emirates-flag.png'),
  LK: require('@homzhub/common/src/assets/flags/srilanka-flag.png'),
  MV: require('@homzhub/common/src/assets/flags/maldives-flag.png'),
  PH: require('@homzhub/common/src/assets/flags/philippines-flag.png'),
  MY: require('@homzhub/common/src/assets/flags/malaysia-flag.png'),
  KP: require('@homzhub/common/src/assets/flags/north-korea-flag.png'),
  KR: require('@homzhub/common/src/assets/flags/south-korea-flag.png'),
  JP: require('@homzhub/common/src/assets/flags/japan-flag.png'),
  CN: require('@homzhub/common/src/assets/flags/china-flag.png'),
  IR: require('@homzhub/common/src/assets/flags/iran-flag.png'),
  RU: require('@homzhub/common/src/assets/flags/russia-flag.png'),
  BR: require('@homzhub/common/src/assets/flags/brazil-flag.png'),
  BD: require('@homzhub/common/src/assets/flags/bangladesh-flag.png'),
  CH: require('@homzhub/common/src/assets/flags/switzerland-flag.png'),
};
